added comments on some functions
mario11596/autoshare_application pull request #26
Opened 2022-04-19 17:08 UTC by mario11596

2022-04-20 20:11 UTC, lmlcvc commented on app/src/main/java/com/riteh/autoshare/adapters/CardListAdapter.kt
Nije suma, nego duljina liste koja se daje u adapter da adapter zna koliko mjesta popuniti (ugrađena funkcija)

2022-04-20 20:12 UTC, lmlcvc commented on app/src/main/java/com/riteh/autoshare/ui/auth/AuthActivity.kt
> + */
Kakav main?

2022-04-20 20:13 UTC, lmlcvc commented on app/src/main/java/com/riteh/autoshare/ui/user/CardNumberFormatX.kt
> +     */
Nije samo za to; ta funkcija ignorira non-digit znakove, umeće "-", pazi na duljinu itd. U biti možeš napisati da formatira upisani tekst.

2022-04-20 20:14 UTC, lmlcvc commented on app/src/main/java/com/riteh/autoshare/ui/user/UserCardInfoActivity.kt
> +     */
Kakav creation alert ?

2022-04-20 20:15 UTC, lmlcvc requested changes
Neki su komentari netočni

2022-04-21 16:38 UTC, mario11596 commented on app/src/main/java/com/riteh/autoshare/ui/auth/AuthActivity.kt
> + */
Glavni aktiviti iz kojeg se pokreće login i registracija.

2022-04-21 20:44 UTC, lmlcvc approved these changes

2022-04-21 20:52 UTC, Darijan23 approved these changes

2022-04-21 20:52 UTC, Darijan23 commented on app/src/main/java/com/riteh/autoshare/adapters/CardListAdapter.kt
> +     * Length list
Za ubuduće, piše se "Length of list" ili "List length", trebalo bi biti ili "_svojstvo_ of _entitet_" ili  "_entitet svojstvo_"

2022-04-21 21:03 UTC, merged